### ISSUE TITLE
사용시 오류가 발생합니다.

### ISSUE THREAD

**Issue by kaczkaduck** [piese1028/galaxycampus-macro#1]
**사용시 알 수 없는 바나나스러운 오류가 발생합니다.**

**Comment by kaczkaduck** [comment]
@piese1028 님의 조치가 필요합니다.

**Comment by piese1028** [comment]
자세한 오류 로그와 스크린샷을 첨부해주세요

**Comment by kaczkaduck** [comment]
![image](https://user-images.githubusercontent.com/63402379/185934540-7258cfd0-1393-45c5-828c-3877349d2faf.png)
첨부한 스크린샷 확인 부탁드립니다.

**Comment by kaczkaduck** [comment]
이슈를 Close하신 이유가 있나요?
